version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
  - package-ecosystem: npm
    directory: /deploy/tencent-cloudbase
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    versioning-strategy: increase-if-necessary
